#include "Player.h"

void C_REQUEST_INGAMESHOP_PRODUCT_LIST_f(player_t *player)
{
	Player_NextHeaderR(player);

printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
printf("-> C_REQUEST_INGAMESHOP_PRODUCT_LIST\n");
}
